services:
  grafana:
    image: grafana/grafana
    platform: linux/amd64
    container_name: grafana_watt
    restart: always
    ports:
      - "3003:3000"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: telegraf
      MYSQL_USER: telegraf
      MYSQL_PASSWORD: telegraf
    ports:
      - "3306:3306"

  telegraf:
    image: telegraf:1.34.0
    container_name: telegraf-watt
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./telegraf:/etc/telegraf
    command: telegraf --config-directory /etc/telegraf
