services:
  grafana:
    image: grafana/grafana
    platform: linux/amd64
    container_name: grafana_watt
    restart: always
    ports:
      - "3000:3000"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: telegraf
      MYSQL_USER: telegraf
      MYSQL_PASSWORD: telegraf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 20s
      timeout: 10s
      retries: 5


  telegraf:
    image: telegraf:1.34.0
    container_name: telegraf-watt
    platform: linux/amd64
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    command: telegraf --config-directory /etc/telegraf
